### ISSUE TITLE
ERROR: Invalid Token. Expected stringEnd but found tag start "{%" instead.

### ISSUE THREAD

**Issue by clevermiraz** [junstyle/vscode-django-support#10]
```html
<div class="card-header">
    <h5 class="card-title">Distributors</h5>
    <a href="{% url 'forum:distributor_create_url' %}" class="btn btn-primary">Add Distributor</a>
</div>
```

I got this error here. `<a href="{% url 'forum:distributor_create_url' %}" class="btn btn-primary">Add Distributor</a>`

How can I resolve that Issue?

Error Is: `ERROR: Invalid Token. Expected stringEnd but found tag start "{%" instead.`

**Comment by junstyle** [comment]
https://github.com/junstyle/vscode-django-support/issues/7

**Comment by clevermiraz** [comment]
Okay, So how can i ignore this Rule Globally? Using prettier.

Not in Scoped.

**Comment by junstyle** [comment]
https://github.com/junstyle/prettier-plugin-django#features

ignore the block

**Comment by clevermiraz** [comment]
> https://github.com/junstyle/prettier-plugin-django#features
> 
> ignore the block

Okay, I know i can Ignore the block.

But is there anyway ignore rule globally?

**Comment by junstyle** [comment]
a new version has been published, now you can use `{%...%}` in html property value d462fcc51610a5e685dd14510c518216e32286dc

**Comment by clevermiraz** [comment]
Awww Thanks, 😊😊

**Comment by clevermiraz** [comment]
> a new version has been published, now you can use `{%...%}` in html property value [d462fcc](https://github.com/junstyle/vscode-django-support/commit/d462fcc51610a5e685dd14510c518216e32286dc)

Awww Thanks, 😊😊
