### ISSUE TITLE
Unnecessary spaces around = in url tags

### ISSUE THREAD

**Issue by lampslave** [junstyle/vscode-django-support#21]
Before formatting:
`{% url 'message-reply' pk=message.pk %}`
After:
`{% url 'message-reply' pk = message.pk %}`
Result:
template error, django cannot parse such url tags

Django Template Support v1.0.26
VSCode 1.82.1

**Comment by smalpas** [comment]
extra spaces added in `{% with %}` tag also occurs after formatting
