### ISSUE TITLE
formatter incompatible {% with business.employees.count as total %}

### ISSUE THREAD

**Issue by CKCat** [junstyle/vscode-django-support#24]
eg: 
```html
{% with business.employees.count as total %} # ERROR: with arguments mismatch. eg: {% with alpha=1 beta=2 %}
```
https://docs.djangoproject.com/en/5.0/ref/templates/builtins/#with

![image](https://github.com/junstyle/vscode-django-support/assets/18586344/c781df96-b109-4d7f-bef0-38f3134402a8)

**Comment by junstyle** [comment]
the old format can use two arguments? or only one argument?

i will fix it
