### ISSUE TITLE
Inline if tags are incorrectly formatted

### ISSUE THREAD

**Issue by sboettcher** [junstyle/vscode-django-support#29]
In an inline if tag like e.g.
```
<div class="{% if flag %}classname{% endif %}"></div>
```
the contents between the if and endif are removed when formatting, resulting in code like
```
<div class="{% if flag %}{% endif %}"></div>
```

Plugin version: `v1.0.33`
VSCode version: `v1.89.1`

**Comment by junstyle** [comment]
fixed

**Comment by dblado** [comment]
I'm still seeing this issue w/ 1.0.35
