### ISSUE TITLE
href="{% url 'index' %}, Error: Invalid Token. Expected stringEnd but found tag start "{%" instead.

### ISSUE THREAD

**Issue by vilkoz** [junstyle/vscode-django-support#3]
```
<a class="navbar-brand" href="{% url 'index' %}">Django</a>
```
ERROR: Invalid Token. Expected stringEnd but found tag start "{%" instead

**Comment by junstyle** [comment]
attribute can't contain tag '{%'. you must use {{ }}

you can use filter in {{ }}

**Comment by vilkoz** [comment]
Another extension works fine in this case, Django also doesn't complain about it.
 P.S. appreciate the work developing the extension, just thought it is unintended behaviour
