### ISSUE TITLE
Formatter compatible with contenteditable <p> fields

### ISSUE THREAD

**Issue by stariluz** [junstyle/vscode-django-support#33]
Given a content editable field as:
```html
<p class="form-control" id="text__editable" role="textbox" contenteditable>{% if form.errors %}{{ form.text.value }}{% endif %}</p>
```
![image](https://github.com/user-attachments/assets/23510311-4bdc-41ed-bcc1-47851a577a26)

The formatter breaks it:
```html
<p class="form-control" id="text__editable" role="textbox" contenteditable>
    {% if form.errors %}{{ form.text.value }}{% endif %}
</p>
```
This results in a wrong behavior of the content editable field.
![image](https://github.com/user-attachments/assets/36dde2fc-3647-4c50-8374-b4cdaf2e468a)

I think that if the tag `<p>` has the `contenteditable` attribute, it shouldn't be broken in more lines.
(The behavior of break lines is not in `span` or `h` tags,  so I'm using them for now).

**Comment by junstyle** [comment]
do you known how to remove useless spaces? read django template doc.

```
{%-   -%}

{{-   -}}
```

**Comment by stariluz** [comment]
What is this supposed to mean?
```
{%-   -%}
{{-   -}}
```
If you mean that I can trip the content of the variable, yes, I can, the problem, is that the blank spaces that are being displayed in the content aren't part of the template variable, they are from the template that is being spaced by the extension.
