### ISSUE TITLE
Not respecting tabSize?

### ISSUE THREAD

**Issue by halfnibble** [junstyle/vscode-django-support#4]
I've configured VSCode to use 4 spaces, but the formatter does not appear to respect my setting.

Is there something I am doing wrong?

**Comment by junstyle** [comment]
formatted by prettier, can automatic search prettier config file in the dirs, such as .prettierrc, .prettier.json...;


you can reference prettier. how to set tabsize

**Comment by jereze** [comment]
Hi everyone,

I'm experiencing a different issue but maybe similar as halfnibble. I added a `.prettierrc` in the root folder (and also in several subfolders just in case) but the formatter does not seem to respect my configuration.

Thanks!

EDIT : my bad, error on my side, after restarting again VScode I can confirm adding a `.prettierrc` works.

**Comment by mjishnu** [comment]
hey!

can you add it as a setting, like "prettier.tabWidth": 4

**Comment by NatanSlvdr** [comment]
Hello, same issue, i get some indents with 4 spaces and other with 2.
Prettier works fine on other files with the right settings :
`
{
"prettier.useTabs": true,
"python.analysis.completeFunctionParens": true,
"editor.formatOnPaste": true,
"editor.formatOnSave": true,
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.insertSpaces": false,
"editor.tabCompletion": "on",
"editor.detectIndentation": false,
"editor.indentSize": "tabSize",
"editor.formatOnType": true,
"prettier.tabWidth": 4,
"[django-html]": {
	"editor.formatOnSave": true,
	"editor.defaultFormatter": "junstyle.vscode-django-support"
}
}
`

**Comment by mjishnu** [comment]
> Hello, same issue, i get some indents with 4 spaces and other with 2. Prettier works fine on other files with the right settings : `{ "prettier.useTabs": true, "python.analysis.completeFunctionParens": true, "editor.formatOnPaste": true, "editor.formatOnSave": true, "editor.defaultFormatter": "esbenp.prettier-vscode", "editor.insertSpaces": false, "editor.tabCompletion": "on", "editor.detectIndentation": false, "editor.indentSize": "tabSize", "editor.formatOnType": true, "prettier.tabWidth": 4, "[django-html]": { "editor.formatOnSave": true, "editor.defaultFormatter": "junstyle.vscode-django-support" } }`

use .prettierrc file it can act as a temp fix

**Comment by junstyle** [comment]
yes. must use a prettier config file, not write in vscode settings. I will close this.

**Comment by mjishnu** [comment]
> yes. must use a prettier config file, not write in vscode settings. I will close this.

hello, can it be possible to also respect setting from vscode settings in future

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hogank, @kong-xc, @ngocmknguyen, @TOSUKUi, @dylantkx, @hossamdarwish, @skynode, @wanderer27k, @schikanski, @949886, @1serafind, @759669271, @TwoWorm, @deanbm, @in1gma, @yefuchao, @codenew0, @MMTE, @georgevella, @lmatt-bit, @bigheadz, @pruthvi578, @martinpavan, @The-Tweak, @imhassla, @mnmlist, @clementizard, @iconben, @jai3lee, @BillyHuihui, @MauNguyenVan, @hamedha1371, @bgramming, @ahnjaehak, @sandeshkatakam, @AlexShee, @taualex, @treehead, @dog5tar, @puleeno, @spoold4, @wilwfy, @falvarez1, @ray2k, @sats, @feigogo, @Zeked9, @oddstab, @hemanth22, @emacsway
