### ISSUE TITLE
Conditionally rendered tags showing errors

### ISSUE THREAD

**Issue by SteveGiralt** [junstyle/vscode-django-support#5]
When conditionally rendering a </tr> tag in a loop, I get an error which breaks formatting on this template. It renders correctly, so the error must be with the extension.

Example Code:
`{% for attachment in question.question_attachments %}
            {% if forloop.counter0|divisibleby:3 %}
            <tr>
              {% endif %}
              <td href="{{ attachment.thumbnail.download_url }}" target="_blank">
                <img src="data:image/jpeg;base64, {{ attachment.thumbnail.thumbnail_base64 }}" width="1.9in" preserveAspectRatio="1" />
                <para style="default">{{ attachment.description }}</para>
              </td>
              {% if forloop.counter|divisibleby:3 or forloop.last %}
              </tr>
              {% endif %}
            {% endfor %}`
 
Error: `ERROR: Expected element start. Unexpected closing "tr" tag. Seems like your DOM is out of control.`

ScreenShot - <img width="927" alt="Screenshot 2023-07-05 at 11 59 33 AM" src="https://github.com/junstyle/vscode-django-support/assets/88471484/ebbd20e6-6e88-4f8b-98d2-d4f9dd1bf582">

**Comment by junstyle** [comment]
because the tag `<tr>` and `</tr>` in different condition block. so you should avoid this situation. make sure start tag and end tag in same block.

**Comment by SteveGiralt** [comment]
Thanks you for your prompt response! This package is a lifesaver! Unfortunately, in this case I can not include both tags in the same condition block. Is there a way to tell the formatter to ignore this so the rest of the file can be formatted?

**Comment by junstyle** [comment]
off course you can ignore that part.


When you are not happy with how Prettier formats a certain element or section in the code, you can tell it to leave it in peace:

```
{# prettier-ignore #}
<div class="weird-formatting" >This will not be re-formatted</div> 
<div class="weird-formatting" >But this will be</div> 
```

You can also tell Prettier to leave entire regions as they are:
```
{# prettier-ignore-start #}
 ... 
{# prettier-ignore-end #}
```

**Comment by SteveGiralt** [comment]
Thank you so much
