### ISSUE TITLE
Removes trailing semi colons from javascript in on-page <script> blocks

### ISSUE THREAD

**Issue by geuis** [junstyle/vscode-django-support#8]
Working in VS Code on a template page that is using <script></script> blocks for javascript.

The formatter removes the semicolons. 

Is this fixable, or a bug?

**Comment by junstyle** [comment]
formatted by prettier, can automatic search prettier config file in the dirs, such as .prettierrc, .prettier.json...;

so you can config to keep or remove `semi`
please read prettier's config referrence
